name: CI

on:
  push:
    tags:
      - '*'

env:
  NODE_JS: "18"

jobs:
  maybe-release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          repository: bpx-chain/synapse-react

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_JS }}
          registry-url: "https://registry.npmjs.org"

      - run: npm install

      - run: npm run build

      - name: Authenticate with registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_SYNAPSE_JS_PUBLISH }}" > ./.npmrc
      
      - run: npm publish --tag latest --access public
